name: Test GCP Authentication

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  test-gcp-auth:
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: projects/912694882726/locations/global/workloadIdentityPools/github-actions/providers/github
          service_account: github-actions@lastfm-data-platform.iam.gserviceaccount.com

      - name: Verify Google Cloud authentication
        run: gcloud auth list